language: python 

python: 
  - "3.6"

services: 
  - postgresql

addons:
  postgresql: "9.6"

env: 
  -DJANGO=1.10 DB=postgresql

install: 
  - pip install -r requirements.txt

before_script: 
  - psql -c "CREATE DATABASE authors_haven;" -U postgres

