language: python 

python: 
  - "3.6"

services: 
  - postgresql

addons:
  postgresql: "9.6"

env: 
  -DJANGO=2.1.7 DB=postgresql

install: 
  - pip install -r requirements.txt

before_script: 
  - psql -c "CREATE DATABASE authors_haven;" -U postgres
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.3/bin/
  - export CHROME_WEBDRIVER=/home/travis/virtualenv/python3.6.3/bin/chromedriver

script:
  - python manage.py test

after_success:
  - coveralls
